[project]
name = "magiport-sc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "mysql-connector-python>=9.4.0",
    "playwright>=1.55.0",
    "requests>=2.32.5",
]
